#!/usr/bin/env bash

## Error handling
abort()
{
    echo >&2 '
***********************************************
*** There was an error running this script. ***
***********************************************
'
    echo "An error occurred. Exiting..." >&2
    exit 1
}

trap 'abort' 0

set -e
## Start script

PROJECTNAME=$1
PROJECTPATH="."
MESSAGE="Initial commit."

while [[ $# -gt 1 ]]
do
    key="$1"

    case $key in
        -p|--path)
            PROJECTPATH="$2"
            shift
            ;;
        -m|--message)
            MESSAGE="$2"
            shift
            ;;
        *)
            ;;
    esac

    shift
done

cd $PROJECTPATH
laravel new $PROJECTNAME
cd $PROJECTNAME
git init
git add .
git commit -m "$MESSAGE"
open "http://$PROJECTNAME.dev"
echo "***********************"
echo "You're ready to go! Remember to cd into $PROJECTNAME before you start editing."

# End script; disable error handling
trap : 0
