#!/usr/bin/env bash

#### Check for project name argument.
if [ $# -eq 0 ]
  then
    echo "Please supply a project name."
    exit 1
fi

## Error handling
abort()
{
    echo >&2 '
***********************************************
*** There was an error running this script. ***
***********************************************
'
    echo "An error occurred. Exiting..." >&2
    exit 1
}

trap 'abort' 0

set -e
## Start script

PROJECTNAME=$1
laravel new $PROJECTNAME
cd $PROJECTNAME
git init
git add .
git commit -m "Initial commit."
open "http://$PROJECTNAME.dev"
echo "***********************"
echo "You're ready to go! Remember to cd into $PROJECTNAME before you start editing."

# End script; disable error handling
trap : 0
