#!/usr/bin/env bash

### Check for project name argument
if [ $# -eq 0 ]
  then
    echo "Please supply a project name."
    exit 1
fi

## Error handling
abort()
{
    echo >&2 '
***********************************************
*** There was an error running this script. ***
***********************************************
'
    echo "An error occurred. Exiting..." >&2
    exit 1
}

quit()
{
    trap : 0
    exit 0
}

trap 'abort' 0

# set -e

## Start script

PROJECTNAME=$1
PROJECTPATH="."
MESSAGE="Initial commit."
BRANCH=""
EDITOR=""

while [[ $# -gt 0 ]]
do
    key="$1"

    case $key in
        -h|--help)
            echo " "
            echo "Lambo: Super-powered Laravel new for Laravel and Valet"
            echo "======================================================"
            echo " "
            echo "lambo myApplication [arguments]"
            echo " "
            echo "options:"
            echo "-h, --help                 show brief help"
            echo "-e, --editor EDITOR        specify an editor to run 'EDITOR .' with after"
            echo "-m, --message \"message\"    customize the initial commit message"
            echo "-p, --path PATH            customize the path in which the new project will be created"
            echo "-d, --develop              use Composer to install on the develop branch" 
            quit
            ;;
        -p|--path)
            PROJECTPATH="$2"
            shift
            ;;
        -m|--message)
            MESSAGE="$2"
            shift
            ;;
        -e|--editor)
            EDITOR="$2"
            shift
            ;;
        -d|--develop)
            BRANCH="develop"
            shift
            ;;
        *)
            ;;
    esac

    shift
done

echo "
***********************************************
Creating new Laravel app $PROJECTNAME
***********************************************
"

cd $PROJECTPATH
if [ "$BRANCH" != "" ]
then
    composer create-project laravel/laravel $PROJECTNAME dev-$BRANCH
else
    laravel new $PROJECTNAME
fi
cd "$PROJECTNAME"
git init
git add .
git commit -m "$MESSAGE"

if [ "$EDITOR" != "" ]
then
    $EDITOR .
fi

# Update .env to point to this database with `root` username and blank pw,
# like Mac MySQL defaults
sed -i '' "/DB_DATABASE/s/homestead/$PROJECTNAME/" .env
sed -i '' '/DB_USERNAME/s/homestead/root/' .env
sed -i '' '/DB_PASSWORD/s/secret//' .env

open "http://$PROJECTNAME.dev"

# @todo: Can we make this work with a ternary style assignment instead?
if [ $PROJECTPATH == "." ]
then
    prettyPath="$PROJECTNAME"
else
    prettyPath="$PROJECTPATH/$PROJECTNAME"
fi

echo "

***********************************************

You're ready to go! Remember to cd into $prettyPath before you start editing."

# End script; disable error handling
trap : 0
