<?php

namespace App\Actions;

use Illuminate\Support\Str;

class UpgradeSavedConfiguration
{
    private $oldConfigurationKeys = [
        'QUIET',
        'AUTH',
        'NODE',
    ];

    public function upgrade(string $savedConfiguration): string
    {
        $commentedConfiguration = collect(explode("\n", $savedConfiguration))->transform(function ($item) {
            $matched = collect($this->oldConfigurationKeys)->reduce(function($carry, $oldKey) use ($item) {
                return $carry || Str::of($item)->startsWith($oldKey);
            }, false);
            return $matched ? "#{$item}" : $item;
        })->implode("\n");

        return "$commentedConfiguration\n{$this->summarizeChanges()}";
    }

    private function summarizeChanges()
    {
        return
'# ------------------------------------------------------------------------------
# 1-APR-2020 5:00 am (auto-generated by Lambo):
# Lambo has commented out the following configuration items as they are no
# longer used, you may safely remove them:
#   QUIET
#   AUTH
#   NODE
# ------------------------------------------------------------------------------';
    }
}
