<?php

namespace Tests;

use LaravelZero\Framework\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        app()->bind('console', function () {
            return new class {
                public function comment($message = '') {}
                public function info() {}
                public function warn($message = '') {}
                public function choice(stirng $choice) {}
            };
        });

        app()->bind('console-writer', function () {
            return new class() {
                public function ok($message): void {}
                public function fail($message): void {}
                public function logStep($message, $verbosity = null) {}
                public function listing(array $items): void {}
                public function table(array $columnHeadings, array $rowData) {}
                public function alert(string $text){}
                public function isDebug(): bool {}
                public function __call($name, $arguments) {}
            };
        });
    }
}
