<?php

namespace Tests\Feature;

use App\Actions\UpgradeSavedConfiguration;
use Carbon\Carbon;
use Tests\TestCase;

class UpgradeSavedConfigurationTest extends TestCase
{
    private $validConfigurationKeys = [
        'VALID_KEY',
        'ANOTHER_VALID_KEY',
    ];

    private $removedConfigurationKeys = [
        'OLD_KEY',
        'ANOTHER_OLD_KEY',
    ];

    private $newConfiguration = [
        'THING' => [
            'commented' => true,
            'default' => 'flibble',
            'description' => [
                'The THING parameter enables Lambo to do a thing.',
                'Valid options are foo, bar and flibble (default if not specified).',
            ],
        ],
        'ANOTHER_THING' => [
            'commented' => false,
            'default' => 'false',
            'description' => [
                'The ANOTHER_THING parameter enables Lambo to do a another thing.',
                'Valid options are true or false (default if not specified).',
            ],
        ],
    ];

    /** @test */
    function it_upgrades_saved_configuration()
    {
        $this->travelTo(Carbon::parse('01-Jan-2000 00:00:00', config('app.timezone')));

        $upgradedConfiguration = app(UpgradeSavedConfiguration::class)->upgrade($this->getConfiguration(), $this->removedConfigurationKeys, $this->newConfiguration);

        $commented =
        'VALID_KEY=foo
ANOTHER_VALID_KEY=foo
#OLD_KEY=foo
#ANOTHER_OLD_KEY=foo


# ------------------------------------------------------------------------------
# 1-Jan-2000 12:00 am (auto-generated by Lambo):
# ------------------------------------------------------------------------------
# Lambo has commented out the following configuration items as they
# are no-longer used. You may safely remove them:
#   OLD_KEY=foo
#   ANOTHER_OLD_KEY=foo

# Lambo has introduced new configuration options. They have been added here
# with sensible defaults; however, you should review them.
#
# The THING parameter enables Lambo to do a thing.
# Valid options are foo, bar and flibble (default if not specified).
#THING=flibble

# The ANOTHER_THING parameter enables Lambo to do a another thing.
# Valid options are true or false (default if not specified).
ANOTHER_THING=false

';

        $this->assertEquals(
            $commented,
            $upgradedConfiguration
        );
    }

    private function getConfiguration(): string
    {
        return collect(array_merge($this->validConfigurationKeys, $this->removedConfigurationKeys))->reduce(function ($carry, $configurationKey) {
            return "{$carry}{$configurationKey}=foo\n";
        }, '');
    }
}
